spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

management:
  endpoint:
    gateway:
      access: read-only
  endpoints:
    web:
      exposure:
        include: gateway,health,info,env