eshoppingzone:
  message: "Config Server is working!"

spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2


management:
  endpoints:
    web:
      exposure:
        include: health,info
      cors:
        allowed-origins: "http://localhost:5173"
        allowed-methods: GET,OPTIONS
        allowed-headers: "*"