spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: "@Bluemoon257"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: "EShoppingZoneSuperSecretKeyForJWT2026SecureKey123456789"